name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lints
      run: cargo || (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y); go || (cd /tmp; wget https://go.dev/dl/go1.20.5.linux-amd64.tar.gz -O go.tgz; tar -xpf go.tgz); source ~/.cargo/env; export PATH=/tmp/go/bin:$PATH; make lint && make test
